# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yash/Desktop/episteme

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yash/Desktop/episteme

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yash/Desktop/episteme/CMakeFiles /home/yash/Desktop/episteme//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yash/Desktop/episteme/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named episteme

# Build rule for target.
episteme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 episteme
.PHONY : episteme

# fast build rule for target.
episteme/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/build
.PHONY : episteme/fast

#=============================================================================
# Target rules for targets named download-net

# Build rule for target.
download-net: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 download-net
.PHONY : download-net

# fast build rule for target.
download-net/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/download-net.dir/build.make CMakeFiles/download-net.dir/build
.PHONY : download-net/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named rebuild

# Build rule for target.
rebuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rebuild
.PHONY : rebuild

# fast build rule for target.
rebuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rebuild.dir/build.make CMakeFiles/rebuild.dir/build
.PHONY : rebuild/fast

#=============================================================================
# Target rules for targets named rebuild-all

# Build rule for target.
rebuild-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rebuild-all
.PHONY : rebuild-all

# fast build rule for target.
rebuild-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rebuild-all.dir/build.make CMakeFiles/rebuild-all.dir/build
.PHONY : rebuild-all/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named both

# Build rule for target.
both: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 both
.PHONY : both

# fast build rule for target.
both/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/both.dir/build.make CMakeFiles/both.dir/build
.PHONY : both/fast

src/engine/chess/move.o: src/engine/chess/move.cpp.o
.PHONY : src/engine/chess/move.o

# target to build an object file
src/engine/chess/move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/move.cpp.o
.PHONY : src/engine/chess/move.cpp.o

src/engine/chess/move.i: src/engine/chess/move.cpp.i
.PHONY : src/engine/chess/move.i

# target to preprocess a source file
src/engine/chess/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/move.cpp.i
.PHONY : src/engine/chess/move.cpp.i

src/engine/chess/move.s: src/engine/chess/move.cpp.s
.PHONY : src/engine/chess/move.s

# target to generate assembly for a file
src/engine/chess/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/move.cpp.s
.PHONY : src/engine/chess/move.cpp.s

src/engine/chess/movegen.o: src/engine/chess/movegen.cpp.o
.PHONY : src/engine/chess/movegen.o

# target to build an object file
src/engine/chess/movegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/movegen.cpp.o
.PHONY : src/engine/chess/movegen.cpp.o

src/engine/chess/movegen.i: src/engine/chess/movegen.cpp.i
.PHONY : src/engine/chess/movegen.i

# target to preprocess a source file
src/engine/chess/movegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/movegen.cpp.i
.PHONY : src/engine/chess/movegen.cpp.i

src/engine/chess/movegen.s: src/engine/chess/movegen.cpp.s
.PHONY : src/engine/chess/movegen.s

# target to generate assembly for a file
src/engine/chess/movegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/movegen.cpp.s
.PHONY : src/engine/chess/movegen.cpp.s

src/engine/chess/perft.o: src/engine/chess/perft.cpp.o
.PHONY : src/engine/chess/perft.o

# target to build an object file
src/engine/chess/perft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/perft.cpp.o
.PHONY : src/engine/chess/perft.cpp.o

src/engine/chess/perft.i: src/engine/chess/perft.cpp.i
.PHONY : src/engine/chess/perft.i

# target to preprocess a source file
src/engine/chess/perft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/perft.cpp.i
.PHONY : src/engine/chess/perft.cpp.i

src/engine/chess/perft.s: src/engine/chess/perft.cpp.s
.PHONY : src/engine/chess/perft.s

# target to generate assembly for a file
src/engine/chess/perft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/perft.cpp.s
.PHONY : src/engine/chess/perft.cpp.s

src/engine/chess/position.o: src/engine/chess/position.cpp.o
.PHONY : src/engine/chess/position.o

# target to build an object file
src/engine/chess/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/position.cpp.o
.PHONY : src/engine/chess/position.cpp.o

src/engine/chess/position.i: src/engine/chess/position.cpp.i
.PHONY : src/engine/chess/position.i

# target to preprocess a source file
src/engine/chess/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/position.cpp.i
.PHONY : src/engine/chess/position.cpp.i

src/engine/chess/position.s: src/engine/chess/position.cpp.s
.PHONY : src/engine/chess/position.s

# target to generate assembly for a file
src/engine/chess/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/position.cpp.s
.PHONY : src/engine/chess/position.cpp.s

src/engine/chess/zobrist.o: src/engine/chess/zobrist.cpp.o
.PHONY : src/engine/chess/zobrist.o

# target to build an object file
src/engine/chess/zobrist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/zobrist.cpp.o
.PHONY : src/engine/chess/zobrist.cpp.o

src/engine/chess/zobrist.i: src/engine/chess/zobrist.cpp.i
.PHONY : src/engine/chess/zobrist.i

# target to preprocess a source file
src/engine/chess/zobrist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/zobrist.cpp.i
.PHONY : src/engine/chess/zobrist.cpp.i

src/engine/chess/zobrist.s: src/engine/chess/zobrist.cpp.s
.PHONY : src/engine/chess/zobrist.s

# target to generate assembly for a file
src/engine/chess/zobrist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/chess/zobrist.cpp.s
.PHONY : src/engine/chess/zobrist.cpp.s

src/engine/evaluation/evaluate.o: src/engine/evaluation/evaluate.cpp.o
.PHONY : src/engine/evaluation/evaluate.o

# target to build an object file
src/engine/evaluation/evaluate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/evaluation/evaluate.cpp.o
.PHONY : src/engine/evaluation/evaluate.cpp.o

src/engine/evaluation/evaluate.i: src/engine/evaluation/evaluate.cpp.i
.PHONY : src/engine/evaluation/evaluate.i

# target to preprocess a source file
src/engine/evaluation/evaluate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/evaluation/evaluate.cpp.i
.PHONY : src/engine/evaluation/evaluate.cpp.i

src/engine/evaluation/evaluate.s: src/engine/evaluation/evaluate.cpp.s
.PHONY : src/engine/evaluation/evaluate.s

# target to generate assembly for a file
src/engine/evaluation/evaluate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/evaluation/evaluate.cpp.s
.PHONY : src/engine/evaluation/evaluate.cpp.s

src/engine/evaluation/nnue.o: src/engine/evaluation/nnue.cpp.o
.PHONY : src/engine/evaluation/nnue.o

# target to build an object file
src/engine/evaluation/nnue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/evaluation/nnue.cpp.o
.PHONY : src/engine/evaluation/nnue.cpp.o

src/engine/evaluation/nnue.i: src/engine/evaluation/nnue.cpp.i
.PHONY : src/engine/evaluation/nnue.i

# target to preprocess a source file
src/engine/evaluation/nnue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/evaluation/nnue.cpp.i
.PHONY : src/engine/evaluation/nnue.cpp.i

src/engine/evaluation/nnue.s: src/engine/evaluation/nnue.cpp.s
.PHONY : src/engine/evaluation/nnue.s

# target to generate assembly for a file
src/engine/evaluation/nnue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/evaluation/nnue.cpp.s
.PHONY : src/engine/evaluation/nnue.cpp.s

src/engine/search/search.o: src/engine/search/search.cpp.o
.PHONY : src/engine/search/search.o

# target to build an object file
src/engine/search/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/search/search.cpp.o
.PHONY : src/engine/search/search.cpp.o

src/engine/search/search.i: src/engine/search/search.cpp.i
.PHONY : src/engine/search/search.i

# target to preprocess a source file
src/engine/search/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/search/search.cpp.i
.PHONY : src/engine/search/search.cpp.i

src/engine/search/search.s: src/engine/search/search.cpp.s
.PHONY : src/engine/search/search.s

# target to generate assembly for a file
src/engine/search/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/search/search.cpp.s
.PHONY : src/engine/search/search.cpp.s

src/engine/search/ttable.o: src/engine/search/ttable.cpp.o
.PHONY : src/engine/search/ttable.o

# target to build an object file
src/engine/search/ttable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/search/ttable.cpp.o
.PHONY : src/engine/search/ttable.cpp.o

src/engine/search/ttable.i: src/engine/search/ttable.cpp.i
.PHONY : src/engine/search/ttable.i

# target to preprocess a source file
src/engine/search/ttable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/search/ttable.cpp.i
.PHONY : src/engine/search/ttable.cpp.i

src/engine/search/ttable.s: src/engine/search/ttable.cpp.s
.PHONY : src/engine/search/ttable.s

# target to generate assembly for a file
src/engine/search/ttable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/search/ttable.cpp.s
.PHONY : src/engine/search/ttable.cpp.s

src/engine/uci/uci.o: src/engine/uci/uci.cpp.o
.PHONY : src/engine/uci/uci.o

# target to build an object file
src/engine/uci/uci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/uci/uci.cpp.o
.PHONY : src/engine/uci/uci.cpp.o

src/engine/uci/uci.i: src/engine/uci/uci.cpp.i
.PHONY : src/engine/uci/uci.i

# target to preprocess a source file
src/engine/uci/uci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/uci/uci.cpp.i
.PHONY : src/engine/uci/uci.cpp.i

src/engine/uci/uci.s: src/engine/uci/uci.cpp.s
.PHONY : src/engine/uci/uci.s

# target to generate assembly for a file
src/engine/uci/uci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/engine/uci/uci.cpp.s
.PHONY : src/engine/uci/uci.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/datagen.o: src/utils/datagen.cpp.o
.PHONY : src/utils/datagen.o

# target to build an object file
src/utils/datagen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/utils/datagen.cpp.o
.PHONY : src/utils/datagen.cpp.o

src/utils/datagen.i: src/utils/datagen.cpp.i
.PHONY : src/utils/datagen.i

# target to preprocess a source file
src/utils/datagen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/utils/datagen.cpp.i
.PHONY : src/utils/datagen.cpp.i

src/utils/datagen.s: src/utils/datagen.cpp.s
.PHONY : src/utils/datagen.s

# target to generate assembly for a file
src/utils/datagen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/utils/datagen.cpp.s
.PHONY : src/utils/datagen.cpp.s

src/utils/format.o: src/utils/format.cpp.o
.PHONY : src/utils/format.o

# target to build an object file
src/utils/format.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/utils/format.cpp.o
.PHONY : src/utils/format.cpp.o

src/utils/format.i: src/utils/format.cpp.i
.PHONY : src/utils/format.i

# target to preprocess a source file
src/utils/format.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/utils/format.cpp.i
.PHONY : src/utils/format.cpp.i

src/utils/format.s: src/utils/format.cpp.s
.PHONY : src/utils/format.s

# target to generate assembly for a file
src/utils/format.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/episteme.dir/build.make CMakeFiles/episteme.dir/src/utils/format.cpp.s
.PHONY : src/utils/format.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... both"
	@echo "... clean-all"
	@echo "... debug"
	@echo "... download-net"
	@echo "... rebuild"
	@echo "... rebuild-all"
	@echo "... release"
	@echo "... episteme"
	@echo "... src/engine/chess/move.o"
	@echo "... src/engine/chess/move.i"
	@echo "... src/engine/chess/move.s"
	@echo "... src/engine/chess/movegen.o"
	@echo "... src/engine/chess/movegen.i"
	@echo "... src/engine/chess/movegen.s"
	@echo "... src/engine/chess/perft.o"
	@echo "... src/engine/chess/perft.i"
	@echo "... src/engine/chess/perft.s"
	@echo "... src/engine/chess/position.o"
	@echo "... src/engine/chess/position.i"
	@echo "... src/engine/chess/position.s"
	@echo "... src/engine/chess/zobrist.o"
	@echo "... src/engine/chess/zobrist.i"
	@echo "... src/engine/chess/zobrist.s"
	@echo "... src/engine/evaluation/evaluate.o"
	@echo "... src/engine/evaluation/evaluate.i"
	@echo "... src/engine/evaluation/evaluate.s"
	@echo "... src/engine/evaluation/nnue.o"
	@echo "... src/engine/evaluation/nnue.i"
	@echo "... src/engine/evaluation/nnue.s"
	@echo "... src/engine/search/search.o"
	@echo "... src/engine/search/search.i"
	@echo "... src/engine/search/search.s"
	@echo "... src/engine/search/ttable.o"
	@echo "... src/engine/search/ttable.i"
	@echo "... src/engine/search/ttable.s"
	@echo "... src/engine/uci/uci.o"
	@echo "... src/engine/uci/uci.i"
	@echo "... src/engine/uci/uci.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/datagen.o"
	@echo "... src/utils/datagen.i"
	@echo "... src/utils/datagen.s"
	@echo "... src/utils/format.o"
	@echo "... src/utils/format.i"
	@echo "... src/utils/format.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

